import type { Metadata } from 'next';
import './globals.css';
import { Lexend } from 'next/font/google';

const lexend = Lexend({
  variable: '--font-lexend',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'eGovChain',
  description: 'Generated by DICT',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const { pathname } = window.location;
                const pathWithoutRepo = pathname.replace('/egovchain-demo', '');
                if (pathname !== pathWithoutRepo) {
                  window.history.replaceState(null, null, pathWithoutRepo);
                }
              })();
            `,
          }}
        />
      </head>
      <body className={`${lexend.variable} antialiased`}>{children}</body>
    </html>
  );
}
